### ISSUE TITLE
Where can I find the documentation on the SPI process?

### ISSUE THREAD

**Issue by matyasf** [PervasiveDisplays/EPD_Driver_GU_mid#1]
I want to drive a 5,8" Pervasive display on a Raspberry Pi via Python, but I could not find any documentation besides this code on how to send data to the EXT3 board. Where can I find this documentation? (its mentioned e.g. here: https://github.com/PervasiveDisplays/EPD_Driver_GU_mid/blob/main/src/EPD_Driver.cpp#L189 ) thanks!

**Comment by arvin-tan** [comment]
Hello @matyasf 

You may find more information on the SPI process in this [document](https://www.pervasivedisplays.com/wp-content/uploads/2019/09/ApplicationNote_EPD740_Mono_with_IST7136_210323.pdf). The document is for a 7.4" display, but the process is similar for a 5.8".
